services:
  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: frontend-dev
    command: npm start -- --host 0.0.0.0
    environment:
      BACKEND_URL: http://backend-dev:8080
    ports:
      - 4200:4200
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - dist/
            - .angular/
        - action: rebuild
          path: ./frontend/package.json

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
      target: dev
    container_name: backend-dev
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      SQL_ENABLED: true
      SPRINGDOC_API_DOCS_ENABLED: true
      SPRINGDOC_SWAGGER_UI_ENABLED: true
    command: sh -c "gradle classes --continuous --no-daemon --watch-fs & gradle bootRun --no-daemon"
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
        - action: rebuild
          path: ./backend/build.gradle.kts

  db:
    build:
      context: ./backend
      dockerfile: Dockerfile-db
    container_name: postgres-db-dev
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - studyplanner_postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  studyplanner_postgres_data:
