services:
  db:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT:-5432}:5432"
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - studyplanner_postgres_data:/var/lib/postgresql
      - ./initialise.sql:/docker-entrypoint-initdb.d/a_initialise.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: gradle:jdk25-corretto
    container_name: backend-dev
    working_dir: /home/gradle/project
    user: gradle
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    volumes:
      - .:/home/gradle/project
      - studyplanner_gradle_cache:/home/gradle/.gradle
    develop:
      watch:
        - action: sync
          path: .
          target: /home/gradle/project
          ignore:
          - .gradle/
          - build/
    command:
      sh -c "chmod +x gradlew && (./gradlew classes --continuous --no-daemon --watch-fs & ./gradlew bootRun --no-daemon)"
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${DB_PORT}/${POSTGRES_DB}

volumes:
  studyplanner_gradle_cache:
  studyplanner_postgres_data:
