FROM gradle:9.3.0-jdk25-corretto AS base
WORKDIR /app

COPY build.gradle.kts settings.gradle.kts ./
COPY gradle/libs.versions.toml gradle/
RUN gradle dependencies --no-daemon

FROM base AS dev
COPY . .

FROM dev AS build
RUN gradle bootJar --no-daemon

FROM eclipse-temurin:25-jre-alpine AS production
WORKDIR /app

RUN addgroup -S app && adduser -S -G app app

COPY --chown=app:app --from=build /app/build/libs/*.jar app.jar

USER app
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
