server: 
  port: ${BACKEND_PORT}

spring:
  application:
    name: study-planner
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: studyplanner
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.xml
    liquibase-schema: studyplanner
  jpa:
    show-sql: ${SQL_ENABLED}

ois:
  base-url: "https://ois2.ut.ee/api"
  
springdoc:
  swagger-ui:
    path: /docs
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED}
  api-docs:
    path: /api/docs
    enabled:  ${SPRINGDOC_API_DOCS_ENABLED}